import type { Roster, BaseCodeCache, PriceData, PricedItem } from "./types";
import { formatTag } from "./format";

export const PRICE_BLOCK_START =
  "// === PD2 PRICE TAGS (generated by pd2_lootfilter) START ===";
export const PRICE_BLOCK_END =
  "// === PD2 PRICE TAGS (generated by pd2_lootfilter) END ===";
export const POTION_BLOCK_START =
  "// === PD2 POTION DISPLAY (generated by pd2_lootfilter) START ===";
export const POTION_BLOCK_END =
  "// === PD2 POTION DISPLAY (generated by pd2_lootfilter) END ===";

/**
 * Static block forcing potions to show at every filter level as minimal
 * symbols. No FILTLVL condition (applies everywhere) and no %CONTINUE% (each
 * rule wins outright, so the Hiim filter's potion-hide rules never run).
 */
export const POTION_BLOCK = [
  POTION_BLOCK_START,
  "ItemDisplay[hp1 OR hp2 OR hp3 OR hp4 OR hp5]: %RED%+",
  "ItemDisplay[mp1 OR mp2 OR mp3 OR mp4 OR mp5]: %BLUE%+",
  "ItemDisplay[rvs]: %PURPLE%*",
  "ItemDisplay[rvl]: %PURPLE%**",
  POTION_BLOCK_END,
].join("\n");

// Ring, amulet, and jewel bases are each shared by 10-20+ distinct items, so a
// `UNI ID rin` / `SET ID amu` / `UNI ID jew` rule matches every ring / amulet /
// jewel in-game. The filter cannot tell them apart, so any price tag on these
// bases is meaningless — exclude them rather than show a misleading range.
const EXCLUDED_BASE_CODES = new Set(["rin", "amu", "jew"]);

/**
 * Pair roster items with their pd2trader price and resolved filter base code.
 * Uniques resolve their base code by uniqueId; sets by name. Items with no
 * price under this name form, no base code, or a base code shared across too
 * many items (rings/amulets/jewels) are dropped. Uniques are de-duplicated by
 * uniqueId — the price check runs before the dedup so an unpriced alias name
 * never blocks the priced form of the same unique.
 */
export function resolvePricedItems(
  roster: Roster,
  cache: BaseCodeCache,
  prices: Map<string, PriceData>,
): PricedItem[] {
  const items: PricedItem[] = [];
  const seenUid = new Set<number>();
  for (const [name, entry] of roster) {
    const price = prices.get(name);
    if (!price) continue;
    if (entry.type === "Unique") {
      if (entry.uniqueId == null || seenUid.has(entry.uniqueId)) continue;
      const baseCode = cache.uniques[String(entry.uniqueId)];
      if (!baseCode || EXCLUDED_BASE_CODES.has(baseCode)) continue;
      seenUid.add(entry.uniqueId);
      items.push({ kind: "unique", baseCode, price });
    } else {
      const baseCode = cache.sets[name];
      if (!baseCode || EXCLUDED_BASE_CODES.has(baseCode)) continue;
      items.push({ kind: "set", baseCode, price });
    }
  }
  return items;
}

/** The filter condition string for a priced item. */
function condition(item: PricedItem): string {
  switch (item.kind) {
    case "unique":
      return `UNI ID ${item.baseCode}`;
    case "set":
      return `SET ID ${item.baseCode}`;
    case "fixed":
      return item.condition;
  }
}

/** Build the delimited price-tag block, one rule per filter condition. */
export function buildBlock(items: PricedItem[]): string {
  const groups = new Map<string, PriceData[]>();
  for (const item of items) {
    const cond = condition(item);
    const arr = groups.get(cond);
    if (arr) arr.push(item.price);
    else groups.set(cond, [item.price]);
  }
  const lines = [PRICE_BLOCK_START];
  for (const [cond, prices] of [...groups.entries()].sort()) {
    lines.push(
      `ItemDisplay[${cond}]: %NAME%%GOLD% | ${formatTag(prices)}%CONTINUE%`,
    );
  }
  lines.push(PRICE_BLOCK_END);
  return lines.join("\n");
}

/** Remove a delimited block (start..end markers), with one blank line each side. */
export function stripBlock(filterText: string, start: string, end: string): string {
  const lines = filterText.split("\n");
  const startIdx = lines.findIndex((l) => l.trim() === start);
  if (startIdx === -1) return filterText;
  let endIdx = -1;
  for (let i = startIdx; i < lines.length; i++) {
    if (lines[i].trim() === end) {
      endIdx = i;
      break;
    }
  }
  if (endIdx === -1) return filterText;
  let from = startIdx;
  let to = endIdx;
  if (from > 0 && lines[from - 1].trim() === "") from -= 1;
  if (to < lines.length - 1 && lines[to + 1].trim() === "") to += 1;
  lines.splice(from, to - from + 1);
  return lines.join("\n");
}

/** Find the line index to insert at: after the last ItemDisplayFilterName line. */
export function findInsertionLine(lines: string[]): number {
  let last = -1;
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].startsWith("ItemDisplayFilterName[]")) last = i;
  }
  return last + 1; // last === -1 -> 0 (top of file)
}

/** Inject the price block and the potion block into the filter text. Idempotent. */
export function decorate(filterText: string, items: PricedItem[]): string {
  let text = stripBlock(filterText, PRICE_BLOCK_START, PRICE_BLOCK_END);
  text = stripBlock(text, POTION_BLOCK_START, POTION_BLOCK_END);
  const lines = text.split("\n");
  const at = findInsertionLine(lines);
  lines.splice(at, 0, "", buildBlock(items), "", POTION_BLOCK, "");
  return lines.join("\n");
}
